[auth]
allowed_redirect_urls = ["http://localhost:3000/auth/callback", "http://localhost:3000/auth/login", "http://localhost:3000/dashboard", "https://linkedin-reviewer.vercel.app/auth/callback", "https://linkedin-reviewer.vercel.app/auth/login", "https://linkedin-reviewer.vercel.app/dashboard"]
require_email_verification = true
verify_email_method = "code"
reset_password_method = "code"

[auth.password]
min_length = 6
require_number = false
require_lowercase = false
require_uppercase = false
require_special_char = false

[auth.smtp]
enabled = false
host = ""
port = 465
username = ""
sender_email = ""
sender_name = ""
min_interval_seconds = 60
